baseURL = 'https://blog.jsph.io/'
languageCode = 'en-us'
title = 'blog.jsph.io'
theme = 'floach'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "the alternative to microsoft dot net"
  # The tagline HTML below the logo (supports HTML for per-letter color accents)
  taglineHTML = '<font color="#A9BC9E">t</font> h e <font color="#A9BC9E">a</font> l t e r n a t i v e <font color="#A9BC9E">t</font> o <font color="#A9BC9E">m</font> i c r o s o f t <font color="#A9BC9E">d</font> o t <font color="#A9BC9E">n</font> e t'
  # The italic quote below the tagline
  quote = "the shell community is full of mountains, valleys, and dangerous cliffs"
  # Logo image settings
  logoImage = "/img/blog_jsph_io_banner_399x66.png"
  logoWidth = 399
  logoHeight = 66
  # News archive heading
  newsArchiveHeading = "News Archive"
  # Footer credit (HTML comment)
  footerCredit = "built with code and hugo"
  # Privacy policy link path (leave empty to hide)
  privacyPolicyPath = "/policy.txt"
  # Background tile credit text (leave empty to hide)
  bgCreditHTML = '(for this background, and many more cool-looking tiles, check out <a href="https://github.com/BenjaminHCCarr/PropagandaTiles">Propaganda</a>.)'

# Footer button images
[params.footer_buttons]
  [[params.footer_buttons.items]]
    url = "https://www.firefox.com/en-US/?redirect_source=mozilla-org"
    image = "/img/firefoxn00bs.gif"
    alt = "Get Firefox"
    width = 88
    height = 31
  [[params.footer_buttons.items]]
    url = "https://github.com/BenjaminHCCarr/PropagandaTiles"
    image = "/img/propaganda.gif"
    alt = "Propaganda Tiles"
    width = 88
    height = 31
  [[params.footer_buttons.items]]
    url = "https://fedoraproject.org/"
    image = "/img/linux_powered.gif"
    alt = "Fedora Linux"
    width = 88
    height = 31
  [[params.footer_buttons.items]]
    url = "https://neocities.org/"
    image = "/img/neocitiespink.gif"
    alt = "Build your own site"
    width = 88
    height = 31

# Secondary footer button (displayed below the main row)
[params.footer_buttons.secondary]
  url = "#"
  image = "/img/sucks.gif"
  alt = "This website sucks"
  width = 106
  height = 24

[taxonomies]
  author = "authors"

[pagination]
  pagerSize = 15

# -------------------------------------------------------
# Sidebar Section Order & Headings
# -------------------------------------------------------
# Each entry defines a sidebar section. The "menu" value must match
# a [[menus.NAME]] group below. "style" is the CSS class for the
# heading: "menuheading" (primary) or "menuheading2" (sub-section).
# Set "headingUrl" to make the heading itself a link.

[[params.sidebar_sections]]
  heading = "Must See Sites"
  menu = "must_see"
  style = "menuheading"

[[params.sidebar_sections]]
  heading = "Old Web"
  menu = "old_web"
  style = "menuheading"

[[params.sidebar_sections]]
  heading = "Cool Apps"
  menu = "cool_apps"
  style = "menuheading2"

# [[params.sidebar_sections]]
#   heading = "LS Modules"
#   menu = "ls_modules"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Last Updated"
#   menu = "ls_modules_updated"
#   style = "menuheading2"

# [[params.sidebar_sections]]
#   heading = "Get Litestep"
#   menu = "get_litestep"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Builds"
#   menu = "get_litestep_builds"
#   style = "menuheading2"

# [[params.sidebar_sections]]
#   heading = "Tutorials"
#   menu = "tutorials"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Mailing Lists"
#   menu = "mailing_lists"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Customizing"
#   menu = "customizing"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Utilities"
#   menu = "utilities"
#   style = "menuheading"

# [[params.sidebar_sections]]
#   heading = "Misc"
#   menu = "misc"
#   style = "menuheading"

# Sidebar button image (bottom of sidebar)
[params.sidebarButton]
  url = "/buttons/"
  image = "/img/fpnbutton04.gif"
  alt = "Click here for more buttons!"
  width = 90
  height = 30

# -------------------------------------------------------
# Sidebar Menus
# -------------------------------------------------------

[[menus.must_see]]
  name = "NetNerds"
  url = "https://blog.netnerds.net/"
  weight = 1
[[menus.must_see]]
  name = "Desktopian.org"
  url = "#"
  weight = 2
[[menus.must_see]]
  name = "DesktopSource"
  url = "#"
  weight = 3
[[menus.must_see]]
  name = "dTOP.org"
  url = "https://www.dtop.org/"
  weight = 4
[[menus.must_see]]
  name = "Mindjunction"
  url = "#"
  weight = 5
[[menus.must_see]]
  name = "Propaganda"
  url = "https://metalab.unc.edu/propaganda/"
  weight = 6
[[menus.must_see]]
  name = "Shell City"
  url = "#"
  weight = 7
[[menus.must_see]]
  name = "ThinkDan"
  url = "#"
  weight = 8
[[menus.must_see]]
  name = "XSWeekly"
  url = "https://www.xsweekly.com/"
  weight = 9

[[menus.old_web]]
  name = "NeoCities"
  url = "https://neocities.org/"
  weight = 1

[[menus.cool_apps]]
  name = "Jellyfin"
  url = "#"
  weight = 1
[[menus.cool_apps]]
  name = "Plex"
  url = "https://www.plex.tv/"
  weight = 1
[[menus.cool_apps]]
  name = "audiobookshelf"
  url = "https://www.audiobookshelf.org/"
  weight = 1
[[menus.cool_apps]]
  name = "Unraid"
  url = "https://unraid.net/"
  weight = 1
[[menus.cool_apps]]
  name = "Lubelogger"
  url = "https://lubelogger.com/"
  weight = 1

[[menus.shells]]
  name = "CodeX"
  url = "#"
  weight = 1
[[menus.shells]]
  name = "core"
  url = "#"
  weight = 2
[[menus.shells]]
  name = "DarkStep"
  url = "#"
  weight = 3
[[menus.shells]]
  name = "Dimension"
  url = "#"
  weight = 4
[[menus.shells]]
  name = "EVWM"
  url = "#"
  weight = 5
[[menus.shells]]
  name = "E-Sense"
  url = "#"
  weight = 6
[[menus.shells]]
  name = "geOShell"
  url = "#"
  weight = 7
[[menus.shells]]
  name = "Graphite"
  url = "#"
  weight = 8
[[menus.shells]]
  name = "IceSphere"
  url = "#"
  weight = 9
[[menus.shells]]
  name = "Litestep"
  url = "#"
  weight = 10
[[menus.shells]]
  name = "OpenView"
  url = "#"
  weight = 11
[[menus.shells]]
  name = "Outsider 99"
  url = "#"
  weight = 12
[[menus.shells]]
  name = "PureLS"
  url = "#"
  weight = 13
[[menus.shells]]
  name = "Reveal"
  url = "#"
  weight = 14
[[menus.shells]]
  name = "Serenade"
  url = "#"
  weight = 15

[[menus.litestep]]
  name = "Litestep.net"
  url = "#"
  weight = 1
[[menus.litestep]]
  name = "Litestep.org"
  url = "#"
  weight = 2
[[menus.litestep]]
  name = "Litestep2000"
  url = "#"
  weight = 3
[[menus.litestep]]
  name = "help.litestep.com"
  url = "#"
  weight = 4
[[menus.litestep]]
  name = "LS Dev Team"
  url = "#"
  weight = 5
[[menus.litestep]]
  name = "LS FAQ"
  url = "#"
  weight = 6
[[menus.litestep]]
  name = "LS Portal"
  url = "#"
  weight = 7
[[menus.litestep]]
  name = "Modulo"
  url = "#"
  weight = 8
[[menus.litestep]]
  name = "stepForum"
  url = "#"
  weight = 9

[[menus.ls_modules]]
  name = "Complete List"
  url = "#"
  weight = 1
[[menus.ls_modules]]
  name = "lscount"
  url = "#"
  weight = 2
  [menus.ls_modules.params]
    important = true

[[menus.tutorials]]
  name = "Upgrading LS"
  url = "#"
  weight = 1
[[menus.tutorials]]
  name = "Debugging LS"
  url = "#"
  weight = 2
[[menus.tutorials]]
  name = "Testing LS"
  url = "#"
  weight = 3
[[menus.tutorials]]
  name = "Multiple Popups"
  url = "#"
  weight = 4
[[menus.tutorials]]
  name = "Shortcut Groups"
  url = "#"
  weight = 5
[[menus.tutorials]]
  name = "Visigoth's Module Tutorial"
  url = "#"
  weight = 6
[[menus.tutorials]]
  name = "LS to PureLS Tutorial"
  url = "#"
  weight = 7

[[menus.mailing_lists]]
  name = "DarkStep"
  url = "#"
  weight = 1
[[menus.mailing_lists]]
  name = "Dimension"
  url = "#"
  weight = 2
[[menus.mailing_lists]]
  name = "ge0Shell"
  url = "#"
  weight = 3
[[menus.mailing_lists]]
  name = "ge0Shell Dev"
  url = "#"
  weight = 4
[[menus.mailing_lists]]
  name = "LS Mailing List"
  url = "#"
  weight = 5
[[menus.mailing_lists]]
  name = "LS-STUFF List"
  url = "#"
  weight = 6
[[menus.mailing_lists]]
  name = "XSWeekly"
  url = "#"
  weight = 7

[[menus.customizing]]
  name = "Styles"
  url = "#"
  weight = 1
[[menus.customizing]]
  name = "Icons"
  url = "#"
  weight = 2

[[menus.utilities]]
  name = "Shell Managers"
  url = "#"
  weight = 1
[[menus.utilities]]
  name = "System"
  url = "#"
  weight = 2
[[menus.utilities]]
  name = "Graphics"
  url = "#"
  weight = 3

[[menus.misc]]
  name = "State of the Step"
  url = "#"
  weight = 1
[[menus.misc]]
  name = "cheggidout archive"
  url = "#"
  weight = 2
[[menus.misc]]
  name = "Articles"
  url = "#"
  weight = 3
[[menus.misc]]
  name = "Site Info"
  url = "#"
  weight = 4
[[menus.misc]]
  name = "Buttons"
  url = "#"
  weight = 5
[[menus.misc]]
  name = "Contact"
  url = "#"
  weight = 6

# Desktop screenshots shown in sidebar
[params.desktops]
  [[params.desktops.items]]
    heading = "root's desktop"
    image = "/img/rootriderss-small.jpg"
    imageAlt = "rootrider's SS"
    imageUrl = "#"
    links = [
      { name = "journal", url = "#" },
      { name = "User #24", url = "#" },
    ]
  [[params.desktops.items]]
    heading = "KuhnDog's desktop"
    image = "/img/kuhndogss-small.jpg"
    imageAlt = "Kuhndog's Screenshot"
    imageUrl = "#"
    links = [
      { name = "User #9", url = "#" },
    ]
